### ISSUE TITLE
metrics 0.17 with metrics-exporter-prometheus build error

### ISSUE THREAD

**Issue by BratSinot** [metrics-rs/metrics#222]
Greetings!

After I upgraded to 0.17 I got a build error. Switching back to 0.16 solve the problem. Tried clean cache and other stuff.
```log
error[E0277]: the trait bound `PrometheusRecorder: Recorder` is not satisfied
  --> server/src/core/app/metrics.rs:18:27
   |
18 |     metrics::set_recorder(&*RECORDER).unwrap();
   |                           ^^^^^^^^^^ the trait `Recorder` is not implemented for `PrometheusRecorder`
   |
   = note: required for the cast to the object type `dyn Recorder`
```
```rust
use metrics_exporter_prometheus::{PrometheusBuilder, PrometheusHandle, PrometheusRecorder};

lazy_static::lazy_static! {
    static ref RECORDER: PrometheusRecorder = PrometheusBuilder::new()
        /*.idle_timeout(
            MetricKindMask::COUNTER | MetricKindMask::HISTOGRAM,
            Some(std::time::Duration::from_secs(10)),
        )*/
        .build();
    static ref HANDLE: PrometheusHandle = RECORDER.handle();
}

pub fn get_metrics() -> String {
    HANDLE.render()
}

pub fn init() {
    metrics::set_recorder(&*RECORDER).unwrap();
}
```

**Comment by tobz** [comment]
Woopsie!

The pains of having so many crates in a pre-1.0 state that depend on each other... 🙈 

I'll cut a new release shortly. 👍🏻

**Comment by tobz** [comment]
Released as `metrics-exporter-prometheus@v0.6.0`.

Sorry about the breakage!
